site_name: NeuroVIP
site_url: https://neurobioinfo.github.io/
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Upload data: upload_data.md
    - Redundant Backups: redundant_backups.md
    - Best Practices for Data Storage: bpds.md
theme: readthedocs

